name: Source Checker

on:
  schedule:
    - cron: "0 23 * * 0"
  push:
#    branches:
#    - dev
    paths:
      - "proxy-build/Asset/sources.txt"
  workflow_dispatch:
    inputs:
      debug:
        description: "Enable Debuging?"
        required: false
        default: "false"
        type: boolean
  repository_dispatch:

permissions:
  contents: write

jobs:
  Check:
    runs-on: ubuntu-latest
    env:
      EnableDebug: ${{ github.event.inputs.debug || 'false' }}
      GithubApiToken: ${{ secrets.GITHUB_TOKEN }}
      GithubRepo: geoasset
      GithubUser: ${{ github.repository_owner }}
      IncludedProtocols: "ss,trojan,vmess,vless"
      LiteConfigPath: Asset/config.json
      LitePath: Asset/lite
      MaxThreadCount: 128
      MinActiveProxies: 1
      SingboxPath: sing-box
      SourcesFile: Asset/sources.txt
      Timeout: 15000

    steps:
      - uses: actions/checkout@v6
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.x

      - name: Install sing-box
        run: |
          sudo dpkg -i proxy-build/Asset/*.deb
          sudo apt-get install -f

      - name: Run source checker
        run: |
          cp -R proxy-build/Asset source-checker/Asset
          cd source-checker

          dotnet restore
          dotnet run --configuration Release --project .
